// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VHS.Data;

#nullable disable

namespace VHS.Data.Core.Migrations
{
    [DbContext(typeof(VHSCoreDBContext))]
    [Migration("20250604115132_add_jobtray_recipe")]
    partial class add_jobtray_recipe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VHS.Data.Models.Audit.OPCAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageInput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageInputDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageOutputDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceiveDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SendDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OPCAudits");
                });

            modelBuilder.Entity("VHS.Data.Models.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Auth.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferredLengthUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredMeasurementSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredTemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredTheme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredVolumeUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredWeightUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BatchPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SeedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrayCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchPlanId");

                    b.HasIndex("FarmId");

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.BatchPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BatchPlanTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaysForPlan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TraysPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("RecipeId");

                    b.ToTable("BatchPlans", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.BatchPlanRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BatchPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchPlanId");

                    b.ToTable("BatchPlanRows", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobLocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderOnDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrayCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.JobTray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLocation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderInJob")
                        .HasColumnType("int");

                    b.Property<int?>("OrderOnLayer")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentJobTrayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLayerId");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId1");

                    b.HasIndex("ParentJobTrayId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TrayId");

                    b.ToTable("JobTrays", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FarmTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FarmTypeId");

                    b.ToTable("Farms", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.FarmType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FarmTypes", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("RackId");

                    b.ToTable("Layers", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LayerCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TrayCountPerLayer")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Racks", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Tray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Trays", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.TrayCurrentState", b =>
                {
                    b.Property<Guid>("TrayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentPhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DestinationLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderOnLayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("SeededDateTimeUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("TrayId");

                    b.HasIndex("BatchId");

                    b.HasIndex("DestinationLayerId");

                    b.HasIndex("JobId");

                    b.HasIndex("LayerId");

                    b.ToTable("TrayCurrentStates", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.TrayTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromPhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToPhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrayId");

                    b.ToTable("TrayTransactions", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.LightZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("TargetDLI")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("LightZones", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.LightZoneSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CalculatedDLI")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Intensity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("LightZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("LightZoneId");

                    b.ToTable("LightZoneSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.WaterZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("TargetDWR")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("WaterZones", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.WaterZoneSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CalculatedDWR")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("WaterZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WaterZoneId");

                    b.ToTable("WaterZoneSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeedIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeedSupplier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GerminationDays")
                        .HasColumnType("int");

                    b.Property<int>("GrowDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PropagationDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.RecipeLightSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LightZoneScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TargetDLI")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LightZoneScheduleId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeLightSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.RecipeWaterSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TargetDWR")
                        .HasColumnType("float");

                    b.Property<Guid>("WaterZoneScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("WaterZoneScheduleId");

                    b.ToTable("RecipeWaterSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Models.Auth.UserSetting", b =>
                {
                    b.HasOne("VHS.Data.Models.Auth.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("VHS.Data.Models.Auth.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.Batch", b =>
                {
                    b.HasOne("VHS.Data.Models.Batches.BatchPlan", "BatchPlan")
                        .WithMany("Batches")
                        .HasForeignKey("BatchPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BatchPlan");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.BatchPlan", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Models.Produce.Recipe", "Recipe")
                        .WithMany("BatchPlans")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Farm");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.BatchPlanRow", b =>
                {
                    b.HasOne("VHS.Data.Models.Batches.BatchPlan", "BatchPlan")
                        .WithMany("BatchPlanRows")
                        .HasForeignKey("BatchPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BatchPlan");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.Job", b =>
                {
                    b.HasOne("VHS.Data.Models.Batches.Batch", "Batch")
                        .WithMany("Jobs")
                        .HasForeignKey("BatchId");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.JobTray", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Layer", "DestinationLayer")
                        .WithMany()
                        .HasForeignKey("DestinationLayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Models.Batches.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Models.Batches.Job", null)
                        .WithMany("Trays")
                        .HasForeignKey("JobId1");

                    b.HasOne("VHS.Data.Models.Batches.JobTray", null)
                        .WithMany()
                        .HasForeignKey("ParentJobTrayId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Models.Produce.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.HasOne("VHS.Data.Models.Farming.Tray", "Tray")
                        .WithMany()
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DestinationLayer");

                    b.Navigation("Job");

                    b.Navigation("Recipe");

                    b.Navigation("Tray");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Farm", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.FarmType", "FarmType")
                        .WithMany("Farms")
                        .HasForeignKey("FarmTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FarmType");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Floor", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany("Floors")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Layer", b =>
                {
                    b.HasOne("VHS.Data.Models.Batches.Job", null)
                        .WithMany("DestinationLayers")
                        .HasForeignKey("JobId");

                    b.HasOne("VHS.Data.Models.Farming.Rack", "Rack")
                        .WithMany("Layers")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Rack", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Floor", "Floor")
                        .WithMany("Racks")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Tray", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.TrayCurrentState", b =>
                {
                    b.HasOne("VHS.Data.Models.Batches.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Models.Farming.Layer", "DestinationLayer")
                        .WithMany()
                        .HasForeignKey("DestinationLayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Models.Batches.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Models.Farming.Layer", null)
                        .WithMany("Trays")
                        .HasForeignKey("LayerId");

                    b.HasOne("VHS.Data.Models.Farming.Tray", "Tray")
                        .WithOne()
                        .HasForeignKey("VHS.Data.Models.Farming.TrayCurrentState", "TrayId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("DestinationLayer");

                    b.Navigation("Job");

                    b.Navigation("Tray");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.TrayTransaction", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Tray", "Tray")
                        .WithMany()
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tray");
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.LightZone", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.LightZoneSchedule", b =>
                {
                    b.HasOne("VHS.Data.Models.Growth.LightZone", "LightZone")
                        .WithMany("LightZoneSchedules")
                        .HasForeignKey("LightZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LightZone");
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.WaterZone", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.WaterZoneSchedule", b =>
                {
                    b.HasOne("VHS.Data.Models.Growth.WaterZone", "WaterZone")
                        .WithMany("WaterZoneSchedules")
                        .HasForeignKey("WaterZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WaterZone");
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.Product", b =>
                {
                    b.HasOne("VHS.Data.Models.Farming.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.Recipe", b =>
                {
                    b.HasOne("VHS.Data.Models.Produce.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.RecipeLightSchedule", b =>
                {
                    b.HasOne("VHS.Data.Models.Growth.LightZoneSchedule", "LightZoneSchedule")
                        .WithMany()
                        .HasForeignKey("LightZoneScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Models.Produce.Recipe", "Recipe")
                        .WithMany("RecipeLightSchedules")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LightZoneSchedule");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.RecipeWaterSchedule", b =>
                {
                    b.HasOne("VHS.Data.Models.Produce.Recipe", "Recipe")
                        .WithMany("RecipeWaterSchedules")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Models.Growth.WaterZoneSchedule", "WaterZoneSchedule")
                        .WithMany()
                        .HasForeignKey("WaterZoneScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("WaterZoneSchedule");
                });

            modelBuilder.Entity("VHS.Data.Models.Auth.User", b =>
                {
                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.Batch", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.BatchPlan", b =>
                {
                    b.Navigation("BatchPlanRows");

                    b.Navigation("Batches");
                });

            modelBuilder.Entity("VHS.Data.Models.Batches.Job", b =>
                {
                    b.Navigation("DestinationLayers");

                    b.Navigation("Trays");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Farm", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.FarmType", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Floor", b =>
                {
                    b.Navigation("Racks");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Layer", b =>
                {
                    b.Navigation("Trays");
                });

            modelBuilder.Entity("VHS.Data.Models.Farming.Rack", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.LightZone", b =>
                {
                    b.Navigation("LightZoneSchedules");
                });

            modelBuilder.Entity("VHS.Data.Models.Growth.WaterZone", b =>
                {
                    b.Navigation("WaterZoneSchedules");
                });

            modelBuilder.Entity("VHS.Data.Models.Produce.Recipe", b =>
                {
                    b.Navigation("BatchPlans");

                    b.Navigation("RecipeLightSchedules");

                    b.Navigation("RecipeWaterSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
