// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VHS.Data.Core;

#nullable disable

namespace VHS.Data.Core.Migrations
{
    [DbContext(typeof(VHSCoreDBContext))]
    [Migration("20250704055507_fix_columns")]
    partial class fix_columns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VHS.Data.Core.Models.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BatchPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SeedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrayCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchPlanId");

                    b.HasIndex("FarmId");

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.BatchPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BatchPlanTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DaysForPlan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TraysPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("RecipeId");

                    b.ToTable("BatchPlans", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.BatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmptyCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("FloorId");

                    b.HasIndex("LayerId");

                    b.HasIndex("RackId");

                    b.ToTable("BatchRows", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FarmTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FarmTypeId");

                    b.ToTable("Farms", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.FarmType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FarmTypes", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobLocationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderOnDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrayCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.JobTray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationLocation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderInJob")
                        .HasColumnType("int");

                    b.Property<int?>("OrderOnLayer")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentJobTrayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransportLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLayerId");

                    b.HasIndex("JobId");

                    b.HasIndex("ParentJobTrayId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TrayId");

                    b.ToTable("JobTrays", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("Layers", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.LightZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("TargetDLI")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("LightZones", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.LightZoneSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CalculatedDLI")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Intensity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("LightZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("LightZoneId");

                    b.ToTable("LightZoneSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeedIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SeedSupplier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LayerCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TrayCountPerLayer")
                        .HasColumnType("int");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Racks", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GerminationDays")
                        .HasColumnType("int");

                    b.Property<int>("GrowDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PropagationDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.RecipeLightSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LightZoneScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TargetDLI")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LightZoneScheduleId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeLightSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.RecipeWaterSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TargetDWR")
                        .HasColumnType("float");

                    b.Property<Guid>("WaterZoneScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("WaterZoneScheduleId");

                    b.ToTable("RecipeWaterSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Tray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("Trays", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.TrayState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArrivedAtSeeder")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ArrivedGrow")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ArrivedHarvest")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ArrivedPaternosterUp")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("ArrivedWashing")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmptyReason")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EmptyToTransplant")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("FinishedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("GrowFinishedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("GrowLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GrowOrderOnLayer")
                        .HasColumnType("int");

                    b.Property<Guid?>("GrowTransportLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("HarvestedWeightKG")
                        .HasColumnType("real");

                    b.Property<DateOnly?>("PreGrowFinishedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PreGrowLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PreGrowOrderOnLayer")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreGrowTransportLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PropagationToTransplant")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("SeedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TransportToHarvest")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("TransportToPaternosterUp")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("TransportToWashing")
                        .HasColumnType("datetime2(7)");

                    b.Property<Guid>("TrayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("WeightRegistered")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("WillBePushedOutGrow")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("WillBePushedOutPreGrow")
                        .HasColumnType("datetime2(7)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("GrowLayerId");

                    b.HasIndex("PreGrowLayerId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TrayId");

                    b.ToTable("TrayStates", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.TrayStateAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OPCAuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrayStateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrayStateId");

                    b.ToTable("TrayStateAudits", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.WaterZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("TargetDWR")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("WaterZones", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.WaterZoneSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CalculatedDWR")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Volume")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("WaterZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WaterZoneId");

                    b.ToTable("WaterZoneSchedules", (string)null);
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Batch", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.BatchPlan", "BatchPlan")
                        .WithMany("Batches")
                        .HasForeignKey("BatchPlanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BatchPlan");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.BatchPlan", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Core.Models.Recipe", "Recipe")
                        .WithMany("BatchPlans")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Farm");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.BatchRow", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Batch", "Batch")
                        .WithMany("BatchRows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Core.Models.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.HasOne("VHS.Data.Core.Models.Layer", "Layer")
                        .WithMany()
                        .HasForeignKey("LayerId");

                    b.HasOne("VHS.Data.Core.Models.Rack", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId");

                    b.Navigation("Batch");

                    b.Navigation("Floor");

                    b.Navigation("Layer");

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Farm", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.FarmType", "FarmType")
                        .WithMany("Farms")
                        .HasForeignKey("FarmTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FarmType");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Floor", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany("Floors")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Job", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Batch", "Batch")
                        .WithMany("Jobs")
                        .HasForeignKey("BatchId");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.JobTray", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Layer", "DestinationLayer")
                        .WithMany()
                        .HasForeignKey("DestinationLayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Core.Models.Job", "Job")
                        .WithMany("JobTrays")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Core.Models.JobTray", "ParentJobTray")
                        .WithMany()
                        .HasForeignKey("ParentJobTrayId");

                    b.HasOne("VHS.Data.Core.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.HasOne("VHS.Data.Core.Models.Tray", "Tray")
                        .WithMany()
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DestinationLayer");

                    b.Navigation("Job");

                    b.Navigation("ParentJobTray");

                    b.Navigation("Recipe");

                    b.Navigation("Tray");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Layer", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Rack", "Rack")
                        .WithMany("Layers")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.LightZone", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.LightZoneSchedule", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.LightZone", "LightZone")
                        .WithMany("LightZoneSchedules")
                        .HasForeignKey("LightZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LightZone");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Product", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Rack", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Floor", "Floor")
                        .WithMany("Racks")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Recipe", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.RecipeLightSchedule", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.LightZoneSchedule", "LightZoneSchedule")
                        .WithMany()
                        .HasForeignKey("LightZoneScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeLightSchedules")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LightZoneSchedule");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.RecipeWaterSchedule", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeWaterSchedules")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VHS.Data.Core.Models.WaterZoneSchedule", "WaterZoneSchedule")
                        .WithMany()
                        .HasForeignKey("WaterZoneScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("WaterZoneSchedule");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Tray", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.TrayState", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId");

                    b.HasOne("VHS.Data.Core.Models.Layer", "GrowLayer")
                        .WithMany("GrowTrayStates")
                        .HasForeignKey("GrowLayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Core.Models.Layer", "PreGrowLayer")
                        .WithMany("PreGrowTrayStates")
                        .HasForeignKey("PreGrowLayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VHS.Data.Core.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.HasOne("VHS.Data.Core.Models.Tray", "Tray")
                        .WithMany("TrayStates")
                        .HasForeignKey("TrayId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Batch");

                    b.Navigation("GrowLayer");

                    b.Navigation("PreGrowLayer");

                    b.Navigation("Recipe");

                    b.Navigation("Tray");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.TrayStateAudit", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.TrayState", "TrayState")
                        .WithMany("TrayStateAudits")
                        .HasForeignKey("TrayStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrayState");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.WaterZone", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.WaterZoneSchedule", b =>
                {
                    b.HasOne("VHS.Data.Core.Models.WaterZone", "WaterZone")
                        .WithMany("WaterZoneSchedules")
                        .HasForeignKey("WaterZoneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WaterZone");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Batch", b =>
                {
                    b.Navigation("BatchRows");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.BatchPlan", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Farm", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.FarmType", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Floor", b =>
                {
                    b.Navigation("Racks");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Job", b =>
                {
                    b.Navigation("JobTrays");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Layer", b =>
                {
                    b.Navigation("GrowTrayStates");

                    b.Navigation("PreGrowTrayStates");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.LightZone", b =>
                {
                    b.Navigation("LightZoneSchedules");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Rack", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Recipe", b =>
                {
                    b.Navigation("BatchPlans");

                    b.Navigation("RecipeLightSchedules");

                    b.Navigation("RecipeWaterSchedules");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.Tray", b =>
                {
                    b.Navigation("TrayStates");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.TrayState", b =>
                {
                    b.Navigation("TrayStateAudits");
                });

            modelBuilder.Entity("VHS.Data.Core.Models.WaterZone", b =>
                {
                    b.Navigation("WaterZoneSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
